before:
  hooks:
    - make man-pages
    - make autocomplete-scripts

builds:
  - main: ./cmd/go-ebsnvme
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath

archives:
  - name_template: '{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}'
    files:
      - README.md
      - LICENSE
      - helpers/*

nfpms:
  - maintainer: &author Maxime VISONNEAU <maxime.visonneau@gmail.com>
    description: Fetch information about AWS EBS NVMe volumes
    license: Apache-2.0
    homepage: https://github.com/mvisonneau/go-ebsnvme
    vendor: *author
    file_name_template: '{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}'
    bindir: /usr/local/sbin
    formats:
      - deb
    contents:
      - src: ./helpers/autocomplete/bash
        dst: /usr/share/bash-completion/completions/{{ .ProjectName }}
        file_info:
          mode: 0644
      - src: ./helpers/autocomplete/zsh
        dst:  /usr/share/zsh/vendor-completions/_{{ .ProjectName }}
        file_info:
          mode: 0644
      - src: ./helpers/manpages/{{ .ProjectName }}.1.gz
        dst: /usr/share/man/man1/{{ .ProjectName }}.1.gz
        file_info:
          mode: 0644
      - src: ./LICENSE
        dst: /usr/share/doc/{{ .ProjectName }}/copyright
        file_info:
          mode: 0644

checksum:
  name_template: '{{ .ProjectName }}_{{ .Tag }}_sha512sums.txt'
  algorithm: sha512

changelog:
  skip: true
