---
language: go
go:
  - '1.11'
go_import_path: github.com/mvisonneau/go-ebsnvme
install:
  - go get -u github.com/mattn/goveralls
script:
  - make all
  - goveralls -service=travis-ci -coverprofile=coverage.out
