---
name: release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
    branches:
      - datadog

jobs:
  release:
    runs-on: ubuntu-22.04

    env:
      DOCKER_CLI_EXPERIMENTAL: 'enabled'

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Install goreleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: v1.21.2
          install-only: true

      - name: Run goreleaser
        run: make ${{ github.ref == 'refs/heads/datadog' && 'pre' || '' }}release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
