---
name: test

on:
  push:
    branches:
      - datadog
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
  pull_request:
    branches:
      - datadog

jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu-22.04

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Lint
        if: ${{ matrix.os == 'ubuntu-22.04' }}
        run: make lint

      - name: Test
        run: make test

      - name: Build
        run: make build